# Generated by Django 4.2.5 on 2023-09-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_generatedimage_prompt_alter_prompt_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='image_url1',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='image_url2',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='image_url3',
            field=models.URLField(default=''),
        ),
    ]
